### ISSUE TITLE
Support for other container runtimes

### ISSUE THREAD

**Issue by goshlanguage** [QuantConnect/lean-cli#121]
Hey team,

First, love the project and thanks for all of your hard work.

Recently I've taken a look at `lean-cli` for personal use. On my laptop, I use `colima` as a replacement for Docker desktop due to the recent controversy surrounding their license agreement.

While my docker cli is mostly compliant via the `podman` interface, the `docker` client for python is hardcoded to only try to connect to the docker socket in `/var/run/docker.sock`

When I would try to run live, I would encounter the error:

```sh
lean live <flags>

Error: Please make sure Docker is installed and running
Visit https://www.lean.io/docs/lean-cli/key-concepts/troubleshooting#02-Common-Errors for more information
```

However, I can symlink the `docker.sock` file in its expected location and get it to run fine:

```sh
sudo ln -s $HOME/.colima/docker.sock /var/run/docker.sock

lean live <flags>

Pulling quantconnect/lean:latest...
latest: Pulling from quantconnect/lean
345e3491a907: Pulling fs layer 
57671312ef6f: Pulling fs layer 
```

Should we try to enumerate some of the docker alternatives and their socket locations to support other docker compliant runtimes, or document how to symlink sockets to the expected path in order to support running `lean-cli` for a broader set of runtime environments?

**Comment by jaredbroad** [comment]
😬 At this point, we're stretched too thin to try and enable support for other non-docker hosts. I would welcome and appreciate a pull-request to enable support for colima but cannot assist in its design.

The top priority currently is to expand the lean-cli to map all the functionality of LEAN. We have so many brokerages and data sources supported in LEAN Core but they're pretty tricky to use since it is all buried in source. The LEAN CLI should able things like:
```
lean data download --source=yfinance AAPL ... 
lean data download --source=iex AAPL ... 
lean data download --source=iqfeed AAPL ... 
```  

We're gearing up for a crowd-raise to try and increase our funding and bandwidth and would appreciate your help to improve the project further. If you like what we're doing, please join us in the raise =)

**Comment by goshlanguage** [comment]
No worries. Best of luck!

**Comment by jowolf** [comment]
I for one would welcome podman compatibility, which is already designed to be a drop-in replacement for docker

j

**Comment by efJerryYang** [comment]
For anyone who encountered the same issue with docker context here, this seems to be a bug in [docker-py](https://github.com/docker/docker-py/issues/3146#issuecomment-1834480674) instead of `lean-cli`, and I believe a better workaround than creating a symbolic link is to overwrite `DOCKER_HOST_PATH` environment variable (and also the `TMPDIR` which is needed specifically for `lean-cli` in my use case).

You can check the context by `docker context ls`.

```shell
export DOCKER_HOST="unix:///Users/<username>/.colima/default/docker.sock"
export TMPDIR="$HOME/.lean/cli-tmp" # needed for local research, not sure for other local run
```
I saved the above lines in a script and load that script in a new shell to run `lean` by aliasing since I don't want to affect the global temp directory.
