### ISSUE TITLE
`lean data generate` fails due to docker requiring sudo

### ISSUE THREAD

**Issue by lilith** [QuantConnect/lean-cli#5]
Making docker run without sudo is a security risk - you're essentially granting root permissions to the user account. 
- https://docs.docker.com/engine/install/linux-postinstall/

Rootless docker installations can't do folder sharing (which I think is used by lean)

lean can't be installed in a way that sudo can find it, AFAICT.

`sudo lean` can't find `lean`
`sudo conda` can't find `conda`

Is there a reasonable workaround for `lean data generate` to work with a typical docker installation?

**Comment by jmerle** [comment]
Thanks for reporting the issue, I missed it myself since I personally do take the risk of adding `$USER` to the `docker` group.

I'll have time to fix this on Tuesday, I think it should be possible for the CLI to automatically elevate itself using `sudo` when needed.

You should already be able run the CLI with `sudo` using `sudo $(which lean)`, but be aware that doing so causes the CLI to use `/root/.lean` as global configuration directory instead of `/home/<username>/.lean`. This is expected with `sudo`, but slightly inconvenient if you usually run the CLI without `sudo`. I'll make sure the CLI does use `/home/<username>/.lean` when it elevates itself and is not explicitly called using `sudo` in the first place.

I'll also look into rootless mode on Tuesday. The CLI does use folder sharing, but from what I can see that is not currently [one of the known limitations of rootless mode](https://docs.docker.com/engine/security/rootless/#known-limitations), so it should already work considering all the folders the CLI mounts into the container are writeable by the user calling the CLI.

**Comment by jmerle** [comment]
This issue is fixed in version 0.1.43, you can use `pip install --upgrade lean` to update. The CLI now automatically elevates itself using `sudo` when necessary. I have also tested the CLI using rootless mode and that works too.

**Comment by lilith** [comment]
Awesome, thank you!
