### ISSUE TITLE
Review Blowfish SSL Encryption deprecation warning

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/lean-cli#509]
<img width="1030" alt="image" src="https://github.com/user-attachments/assets/e14f0061-b909-4ea9-903e-123b78f6a692">

Review associated dependency and whether we should replace or just update

**Comment by Marinovsky** [comment]
We tried to reproduce the warning but we couldn't since:
1. The warning was thrown by paramiko, a dependency of a library we use in lean-cli (we think it might be Docker: https://github.com/docker/docker-py/blob/bb0edd1f6655f06d8522879429584d90747dafe2/pyproject.toml#L41)
2. The part of code in paramiko that was throwing the warning was deprecated and removed: https://github.com/paramiko/paramiko/pull/2039/files

Besides, when using Python 3.12 and cryptography==43.0.3 85 tests fail (Here the [logs.txt](https://github.com/user-attachments/files/17590919/logs.txt))
):
![image](https://github.com/user-attachments/assets/7ebec44f-5088-4521-a411-e4c7b8114203)
