### ISSUE TITLE
Adding config.json on project creation and usability improvements on notebooks

### ISSUE THREAD

**Issue by bmello4688** [QuantConnect/lean-cli#6]
This allows a person who creates a project to be 95% of the way to running the generated jupyter notebooks. The data-folder just needs to be changed to the folder where lean init was run.

Notebook cells arranged for showing of logs in case of error

**Comment by jmerle** [comment]
How are you running the research environment? Are you manually running the `quantconnect/research` image using `docker`, or are you using `lean research`? The `config.json` file is filled with the necessary details when you run the command `lean research` command.

**Comment by bmello4688** [comment]
I am using docker run/docker compose. I am using docker as a research/dev environment with vscode. So I actually run the cli from within the container. I also run my workspace side-by-side to the lean engine so I also need a way to reference the engine location. I would never use any of the commands that create a new docker container. In my opinion, create_project should be the one creating the config file so that I can run my project anywhere. I believe I need a config.json for local backtest running or local live running? It doesn't look like configs are generated for those.

**Comment by bmello4688** [comment]
Also in the documentation it says "This file is automatically generated when you run lean create-project or lean cloud pull. "

https://www.quantconnect.com/docs/v2/lean-cli/user-guides/configuration

**Comment by jmerle** [comment]
You're right in that the generated config files are not complete, because the CLI automatically generates the missing parts when you run a command like `lean backtest` or `lean research`. When you do so, the CLI automatically mounts a config file containing all required properties, filling in the missing properties based on the arguments you give to its commands (like the environment, the location of the algorithm file, etc.) and based on information you provided in the past (like your user id and API token). The configuration files that the CLI documentation refers to are the CLI's configuration files, not LEAN's ones.

What you're trying to do, mixing the CLI with manual Docker usage, is not what the CLI is made for. The goal of this CLI is to make it as easy as possible to run the LEAN engine, meaning the CLI manages everything related to Docker (pulling images, running containers, etc.).

Because you said you are working side-by-side with the LEAN engine: since last week we also support [using custom Docker images with the CLI](https://www.quantconnect.com/docs/v2/lean-cli/tutorials/customizing-lean), so if you have a custom fork of LEAN you can use the [`lean build`](https://www.quantconnect.com/docs/v2/lean-cli/api-reference/lean-build) command to turn that into a Docker image and run it through the CLI.

**Comment by bmello4688** [comment]
That is fine. I guess I'm really looking to just use the project management features of the cli. I'll just fork and create a subset of the tool that does what I need. Thank you for your help
