### ISSUE TITLE
Invalid Backtest Url and --open Does Not Open to Backtest page

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/lean-cli#61]
```
(base) PS C:\Users\Alex\Local> lean cloud backtest "RiskAverse2" --push --open
[1/1] Pushing 'RiskAverse2'
Successfully updated cloud file 'RiskAverse/main.py'
Started compiling project 'RiskAverse'
Detected parameters: none
Build Request Successful for Project ID: 10244769, with CompileID:
053f5b0cdd39550264ff5d8cc8724370-08219cfbd61c7f9e413b570308392826, Lean Version: 2.5.0.0.13520
Successfully compiled project 'RiskAverse'
Started backtest named 'Geeky Orange Snake' for project 'RiskAverse'
Backtest url: https://www.quantconnect.com/terminal/#open/10244769/922781a33f82d756c2fa67aa3b6597ab
 ---------------------------------------- 0%
Backtest id: 922781a33f82d756c2fa67aa3b6597ab
Backtest name: Geeky Orange Snake
Backtest url: https://www.quantconnect.com/terminal/#open/10244769/922781a33f82d756c2fa67aa3b6597ab
```

The https://www.quantconnect.com/terminal/#open/10244769/922781a33f82d756c2fa67aa3b6597ab doesn't open the backtest tab.. It opens that Terminal page instead.

**Comment by shootdaj** [comment]
Any updates on this? It has been over 6 months and I'm still encountering the same issue...

**Comment by shootdaj** [comment]
I found the line that needs to be changed: 

https://github.com/QuantConnect/lean-cli/blob/23a4092543922df5f85e71a9fb6718ecde3320bb/lean/models/api.py#L191

Seems like the backtest itself doesn't have a URL since you have changed the way the terminal works but can you at least change it such that it opens the project?

I believe all that needs to be done is to change the "terminal/#open" with "project" and that will open the project.

@jaredbroad tagging you as I'm not sure who works on that feature. Thank you.
